# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-11-26 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('vote_count', models.IntegerField(default=0)),
            ],
        ),
    ]
