name: Django Application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt
      - name: Run migrations
        run: python manage.py migrate
      - name: Run tests
        run: python manage.py test

  terraform-run:
    name: 'Terraform Run'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/workflows/data/local
    steps:
    - uses: hashicorp/setup-terraform@v1
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: ./

    - name: Terraform Init
      shell: bash
      run: terraform init

    - name: Terraform Format
      shell: bash
      run: terraform fmt -check

    - name: Terraform Plan
      id: plan
      shell: bash
      run: terraform plan

    - name: Print Terraform Plan
      shell: bash
      run: echo "${{ steps.plan.outputs.stdout }}"