name: Django Application
on: [push]
jobs:
  terraform-run:
    name: 'Terraform Run'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/workflows/data/local
    steps:
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: ./

    - name: Terraform Init
      shell: bash
      run: terraform init

    - name: Terraform Format
      shell: bash
      run: terraform fmt -check

    - name: Terraform Plan
      id: plan
      shell: bash
      run: terraform plan

    - name: Print Terraform Plan
      shell: bash
      run: echo "${{ steps.plan.outputs.stdout }}"